### ISSUE TITLE
Not able to launch the thing

### ISSUE THREAD

**Issue by TyrfingMjolnir** [Jinmo/applescript-disassembler#1]
$ python2 ./disassembler.py /opt/dev/applescript/some.scpt
Traceback (most recent call last):
  File "./disassembler.py", line 153, in <module>
    main()
  File "./disassembler.py", line 20, in main
    f = load_file(path)
  File "/opt/dev/applescript-disassembler/engine/fasparser.py", line 253, in load_file
    r = readObject(0)
  File "/opt/dev/applescript-disassembler/engine/fasparser.py", line 223, in readObject
    data = readValueBlock(id, size)
  File "/opt/dev/applescript-disassembler/engine/fasparser.py", line 90, in readValueBlock
    r = _readRefList(size)
  File "/opt/dev/applescript-disassembler/engine/fasparser.py", line 78, in _readRefList
    R.append(findObject(refId))
  File "/opt/dev/applescript-disassembler/engine/fasparser.py", line 66, in findObject
    refMap[refId] = readObject(refId)
  File "/opt/dev/applescript-disassembler/engine/fasparser.py", line 227, in readObject
    data = readUntypedPointerBlock(id, size)
  File "/opt/dev/applescript-disassembler/engine/fasparser.py", line 101, in readUntypedPointerBlock
    r = _readRefList(size)
  File "/opt/dev/applescript-disassembler/engine/fasparser.py", line 78, in _readRefList
    R.append(findObject(refId))
  File "/opt/dev/applescript-disassembler/engine/fasparser.py", line 66, in findObject
    refMap[refId] = readObject(refId)
  File "/opt/dev/applescript-disassembler/engine/fasparser.py", line 223, in readObject
    data = readValueBlock(id, size)
  File "/opt/dev/applescript-disassembler/engine/fasparser.py", line 90, in readValueBlock
    r = _readRefList(size)
  File "/opt/dev/applescript-disassembler/engine/fasparser.py", line 78, in _readRefList
    R.append(findObject(refId))
  File "/opt/dev/applescript-disassembler/engine/fasparser.py", line 66, in findObject
    refMap[refId] = readObject(refId)
  File "/opt/dev/applescript-disassembler/engine/fasparser.py", line 227, in readObject
    data = readUntypedPointerBlock(id, size)
  File "/opt/dev/applescript-disassembler/engine/fasparser.py", line 101, in readUntypedPointerBlock
    r = _readRefList(size)
  File "/opt/dev/applescript-disassembler/engine/fasparser.py", line 78, in _readRefList
    R.append(findObject(refId))
  File "/opt/dev/applescript-disassembler/engine/fasparser.py", line 66, in findObject
    refMap[refId] = readObject(refId)
  File "/opt/dev/applescript-disassembler/engine/fasparser.py", line 229, in readObject
    data = readCodeId(size)
  File "/opt/dev/applescript-disassembler/engine/fasparser.py", line 111, in readCodeId
    constTable[v] = v
NameError: global name 'constTable' is not defined

**Comment by TyrfingMjolnir** [comment]
I patched my fork to make it work: https://github.com/TyrfingMjolnir/applescript-disassembler/blob/master/engine/fasparser.py#L111

**Comment by Jinmo** [comment]
Thanks for the report! I forgot to update some bugfixes. I pushed the patch. Can I ask is it working now?

**Comment by TyrfingMjolnir** [comment]
If you clone from my user it should work.

**Comment by TyrfingMjolnir** [comment]
There are some more stuff that I did on my repo, but I'm not able to make another PR in the web inteface, I find web interfaces confusing.

**Comment by Jinmo** [comment]
Thanks! I'll check the PR now.
