### ISSUE TITLE
Exception: Error -1702: unknown object type: 19!

### ISSUE THREAD

**Issue by LOVEChen** [Jinmo/applescript-disassembler#6]
```
 python3 disassembler.py main.scpt
Traceback (most recent call last):
  File "/Users/love/Downloads/applescript-disassembler-master/disassembler.py", line 221, in <module>
    main()
  File "/Users/love/Downloads/applescript-disassembler-master/disassembler.py", line 24, in main
    f = f.load(path)
  File "/Users/love/Downloads/applescript-disassembler-master/engine/fasparser.py", line 269, in load
    self.loadTable.loadObject(0)
  File "/Users/love/Downloads/applescript-disassembler-master/engine/fasparser.py", line 128, in loadObject
    self.loadObjectBody(num, context.index, context.inlined)
  File "/Users/love/Downloads/applescript-disassembler-master/engine/fasparser.py", line 159, in loadObjectBody
    t(self, ref, inlined)
  File "/Users/love/Downloads/applescript-disassembler-master/engine/fasobjects/valueblock.py", line 21, in load
    res = refloader.doLoad()
  File "/Users/love/Downloads/applescript-disassembler-master/engine/fasobjects/util.py", line 25, in doLoad
    self.table.findObject(self.refs[i].value)
  File "/Users/love/Downloads/applescript-disassembler-master/engine/fasparser.py", line 181, in findObject
    self.loadObject(num)
  File "/Users/love/Downloads/applescript-disassembler-master/engine/fasparser.py", line 128, in loadObject
    self.loadObjectBody(num, context.index, context.inlined)
  File "/Users/love/Downloads/applescript-disassembler-master/engine/fasparser.py", line 159, in loadObjectBody
    t(self, ref, inlined)
  File "/Users/love/Downloads/applescript-disassembler-master/engine/fasobjects/untyped_pointer_block.py", line 10, in load_untypedPointerBlock
    vector = refs.doLoad()
  File "/Users/love/Downloads/applescript-disassembler-master/engine/fasobjects/util.py", line 25, in doLoad
    self.table.findObject(self.refs[i].value)
  File "/Users/love/Downloads/applescript-disassembler-master/engine/fasparser.py", line 181, in findObject
    self.loadObject(num)
  File "/Users/love/Downloads/applescript-disassembler-master/engine/fasparser.py", line 128, in loadObject
    self.loadObjectBody(num, context.index, context.inlined)
  File "/Users/love/Downloads/applescript-disassembler-master/engine/fasparser.py", line 159, in loadObjectBody
    t(self, ref, inlined)
  File "/Users/love/Downloads/applescript-disassembler-master/engine/fasobjects/valueblock.py", line 21, in load
    res = refloader.doLoad()
  File "/Users/love/Downloads/applescript-disassembler-master/engine/fasobjects/util.py", line 25, in doLoad
    self.table.findObject(self.refs[i].value)
  File "/Users/love/Downloads/applescript-disassembler-master/engine/fasparser.py", line 181, in findObject
    self.loadObject(num)
  File "/Users/love/Downloads/applescript-disassembler-master/engine/fasparser.py", line 128, in loadObject
    self.loadObjectBody(num, context.index, context.inlined)
  File "/Users/love/Downloads/applescript-disassembler-master/engine/fasparser.py", line 159, in loadObjectBody
    t(self, ref, inlined)
  File "/Users/love/Downloads/applescript-disassembler-master/engine/fasobjects/untyped_pointer_block.py", line 10, in load_untypedPointerBlock
    vector = refs.doLoad()
  File "/Users/love/Downloads/applescript-disassembler-master/engine/fasobjects/util.py", line 25, in doLoad
    self.table.findObject(self.refs[i].value)
  File "/Users/love/Downloads/applescript-disassembler-master/engine/fasparser.py", line 181, in findObject
    self.loadObject(num)
  File "/Users/love/Downloads/applescript-disassembler-master/engine/fasparser.py", line 128, in loadObject
    self.loadObjectBody(num, context.index, context.inlined)
  File "/Users/love/Downloads/applescript-disassembler-master/engine/fasparser.py", line 159, in loadObjectBody
    t(self, ref, inlined)
  File "/Users/love/Downloads/applescript-disassembler-master/engine/fasobjects/valueblock.py", line 21, in load
    res = refloader.doLoad()
  File "/Users/love/Downloads/applescript-disassembler-master/engine/fasobjects/util.py", line 25, in doLoad
    self.table.findObject(self.refs[i].value)
  File "/Users/love/Downloads/applescript-disassembler-master/engine/fasparser.py", line 181, in findObject
    self.loadObject(num)
  File "/Users/love/Downloads/applescript-disassembler-master/engine/fasparser.py", line 128, in loadObject
    self.loadObjectBody(num, context.index, context.inlined)
  File "/Users/love/Downloads/applescript-disassembler-master/engine/fasparser.py", line 153, in loadObjectBody
    raise Exception('Error -1702: unknown object type: %d!' % index)
Exception: Error -1702: unknown object type: 19!
```

**Comment by Jinmo** [comment]
Hello, could you try 146bd19bb34dfdd44709e26f3cd44c1c919e588b ?

**Comment by LOVEChen** [comment]
> 

Thank you reply,

worked!
